name = "DTCInitium"
uuid = "e2b5b24c-ed1b-4dfa-a7f0-df40ce9b2526"
authors = ["Paulo Jabardo <pjabardo@ipt.br>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.7"

[targets]
test = ["Test"]
